### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by rejas**
Update to latest bin-wrapper to fix warnings when doing npm isntall

### CODE REVIEW

**Comment by rejas** [comment]
Is the group still active at all @sindresorhus ?

**Comment by yetzt** [comment]
whats taking so long?

**Comment by rejas** [comment]
I have no idea so I opened an issue asking the maintainers if they consider imagemin dead....

**Comment by rejas** [comment]
@1000ch Fixed.

**Comment by 1000ch** [comment]
@rejas Sorry again, squash commits?

**Comment by rejas** [comment]
@1000ch not sure how I can do that, squashing as far as I know can only do the maintainer when he merges the branch.

**Comment by 1000ch** [comment]
@rejas I mean you can do it on your branch using [`git rebase`](https://git-scm.com/docs/git-rebase).

**Comment by rejas** [comment]
Since I am not in front of my work pc, I'd be very glad if you could use the squash-button on github to do this.

**Comment by rejas** [comment]
Squashed it @1000ch Can you merge and release it now?

**Pull request merged**
