### PR TITLE
Added Windows binaries for mozjpeg 3.0

### PR DESCRIPTION
**Pull request by michel-kraemer**
As requested in https://github.com/imagemin/imagemin-mozjpeg/issues/3#issuecomment-71347212 I built mozjpeg 3.0 for Windows. This should fix issue #7. I guess 32 bits is OK? If not, I can of course build the 64-bit version as well.

### CODE REVIEW

**Comment by shinnn** [comment]
> I guess 32 bits is OK? If not, I can of course build the 64-bit version as well.

Could you add both 32-bit build and 64-bit build like this? https://github.com/imagemin/jpegtran-bin/tree/master/vendor/win

**Comment by kevva** [comment]
The 32 bit seems to work fine for me on x64 too.

**Comment by shinnn** [comment]
OK, merge?

**Comment by kevva** [comment]
Merge. Ty @michel-kraemer!

**Pull request merged**
